version: 2.1

orbs:
  node: circleci/node@4.2.0
  codecov: codecov/codecov@1.0.2
  chromatic: wave/chromatic@1.3.0
jobs:
  build:
    docker:
      - image: cimg/node:15.1

    working_directory: ~/repo

    steps:
      - checkout 
      - node/install-packages:
          pkg-manager: yarn
      
      - run:
          name: Build 
          command: yarn build-storybook -o ./dist

      - run:
          name: Coverage
          command: yarn test:coverage 

      - store_test_results:
          path: ./test-results 

      - store_artifacts:
          path: ./test-results

      - codecov/upload:
          file: './coverage/clover.xml'

      - chromatic/test:
          CHROMATIC_APP_CODE: 6040710bee40c900232c1880
          CHROMATIC_PROJECT_TOKEN: ${CHROMATIC_PROJECT_TOKEN}

