version: 2.1

orbs:
  node: circleci/node@4.2.0
jobs:
  build:
    docker:
      - image: cimg/node:15.1

    working_directory: ~/repo

    steps:
      - checkout 
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run tests
          command: yarn test

