version: 2.1

orbs:
  node: circleci/node@4.2.0
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: cimg/node:15.1

    working_directory: ~/repo

    steps:
      - checkout 
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run tests
          command: yarn test

      - run:
          name: Build 
          command: yarn build-storybook -o ./dist

      - run:
          name: Coverage
          command: yarn test:coverage 

      - store_test_results:
          path: ./reports/junit/

      - store_artifacts:
          path: ./reports/junit

      - codecov/upload:
          file: './coverage/clover.xml'

